// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPqxU5i87SC3Av87MNjk_F4KDI3iVKp3Y',
    appId: '1:190448865971:web:2381aa334a8db9b1dd16c6',
    messagingSenderId: '190448865971',
    projectId: 'mintrix-a83df',
    authDomain: 'mintrix-a83df.firebaseapp.com',
    storageBucket: 'mintrix-a83df.firebasestorage.app',
    measurementId: 'G-0GQ1YJ76CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPZCxOoN_Iae2-fcg1QWBWWa6zw71PcY',
    appId: '1:190448865971:android:dbd5190f2bd5f6c9dd16c6',
    messagingSenderId: '190448865971',
    projectId: 'mintrix-a83df',
    storageBucket: 'mintrix-a83df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8WOfHU7c3pZuM1IlqxULWQfhedAY1oG0',
    appId: '1:190448865971:ios:996bbf4c007ac4a3dd16c6',
    messagingSenderId: '190448865971',
    projectId: 'mintrix-a83df',
    storageBucket: 'mintrix-a83df.firebasestorage.app',
    iosClientId: '190448865971-bs9epb201tg5rcnh1r74hp2r63tmtncp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mintrix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8WOfHU7c3pZuM1IlqxULWQfhedAY1oG0',
    appId: '1:190448865971:ios:996bbf4c007ac4a3dd16c6',
    messagingSenderId: '190448865971',
    projectId: 'mintrix-a83df',
    storageBucket: 'mintrix-a83df.firebasestorage.app',
    iosClientId: '190448865971-bs9epb201tg5rcnh1r74hp2r63tmtncp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mintrix',
  );

}